version: '3.8'

services:
# [TODO]: open when need to deploy
# NEXT
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGODB_URI=mongodb://mongo:27017/relieve_project
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/app
# MONGO
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/relieve_project
    volumes:
      - mongo-data:/data/db

volumes:
    mongo-data: 

