version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data: